---
title: "Equations and algorithms"
author: "Christophe Gigot"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Equations and algorithms}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

## Definitions

Throughout this package, we took care to stay consistent regarding the name of variables. The more important ones are the followings:

- $x, y, z$ corresponds to the spatial dimensions,
- $t$ corresponds to the time
- $d$ corresponds to the value of disease intensity, in general, when no distinction is desired. 
- $d$ and $D$ corresponding to the value of disease intensity assessment. When no distinction is desired. $D \in \mathbb{N}_0 = \{0, 1, 2, \ldots\}$ and $d \in [0, 1]$. Basically:
    - only $D$ makes sense for count data,
    - $d = D/n$ for incidence data,
    - only $d$ makes sense for severity data.
    
$$p = \bar{d} = \frac{\sum_i d_i}{N} = \frac{\sum_i (D_i / n_i)}{N}$$

$$P = \frac{\sum_i D_i}{N}$$

Note that in R-code, only `d` is used.
    
- $n$ (`n` in R-code): the number of elements in a sampling unit. Note that currently most of the methods only work with equal size sampling units (only one `n` per data set).
- $N$ (`N` in R-code): the number of sampling units in a data set.
- $\theta$ (`theta` in R-code): The aggregation parameter computed from the two shape parameters of the beta-binomial distribution, $alpha$ and $beta$. Be careful, the definition here is: $\theta = 1 / (\alpha + \beta)$, which is unfortunatelly not necessarily consistent which what can be found in the litterature. For instance, in `VAGM` (TO CHECK) and `emdbook` packages, the definition is $\theta = \alpha + \beta$.

## Equations

## Algos

Beta-binomial

The compound distribution is given by:

$$
f(d|n,\alpha,\beta) = \binom{n}{d} \frac{B(d + \alpha, n - d + \beta)}{B(\alpha, \beta)}
$$

There are two implementations:

1. Similar to the one used in BBD [@Madden_etal]


$$
\ln \left[ \Gamma(n+1) \right] - \ln \left[ \Gamma(x+1) \right]
$$


```
        -sum((lgamma(n+1)-lgamma(x+1)-lgamma(n-x+1))+
            lgamma((p/theta)+((1-p)/theta))+
            lgamma((p/theta)+x)+
            lgamma(((1-p)/theta)+n-x)-
            (lgamma(p/theta)+lgamma((1-p)/theta)+lgamma((p/theta)+((1-p)/theta)+n)))

```

2. And the one similar to the APS website

$$
\binom{n}{d} \frac{\Gamma(\alpha + d) \Gamma(n - d + \beta)}{\Gamma(n + \alpha + \beta)} \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha)\Gamma(\beta)}
$$

Using the natural logarithm, we get:

$$
\ln\left[ \binom{n}{d} \right] + \ln\left[ \Gamma(\alpha + \beta) \right] + \ln \left[ \Gamma(n - d + \beta) \right] - \ln \left[ \Gamma(n + \alpha + \beta) \right] + \ln \left[ \Gamma(\alpha + \beta) \right] - \ln \left[ \Gamma(\alpha) \right] - \left[ \Gamma(\beta) \right]
$$

Which can be easily implemented with R-syntax:


```r
lchoose(n, d)+lgamma(alpha+beta)+lgamma(n-d+beta)-lgamma(n+alpha+beta)+lgamma(alpha+beta)-lgamma(alpha)-lgamma(beta)
```


```r
        sum(-lgamma(alpha+x)-lgamma(beta+n-x)+lgamma(alpha+beta+n)
            +lgamma(alpha)+lgamma(beta)-lgamma(alpha+beta))

```


## Appendix/Memento

### $p, \theta, \rho, \alpha \text{ and } \beta$

|   |1  |   |   |
|---|---|---|---|
| $$f(\alpha, \beta)$$ | $$p = \frac{\alpha}{\alpha + \beta};$$ | $$\theta = \frac{1}{\alpha + \beta};$$ | $$\rho = \frac{1}{\alpha + \beta + 1}$$ |
| $$f(\theta, \rho)$$ | $$\theta = \frac{\rho}{1 - \rho};$$ | $$\rho = \frac{\theta}{\theta + 1}$$ | |
| $$f(p, \theta)$$ | $$\alpha = \frac{p}{\theta};$$ | $$\beta = \frac{1 - p}{\theta}$$ | |
| $$f(p, \rho)$$ | $$\alpha = \frac{p(1-\rho)}{\rho};$$ | $$\beta = \frac{(1 - p)(1-\rho)}{\rho}$$ | |

### Power Law

Different parametrizations are available, and you must be careful when making comparaisons/computations.

Two formulas:

$$
s_{obs}^2 = V_n = A_n [np(1-p)]^b = a_n [p(1-p)]^b
$$

$$
s_{obs}^2 = V_p = A_p [p(1-p)/n]^b = a_p [p(1-p)]^b
$$

$$
V_n = n^2 V_p
$$

|       | $A_p$                  | $a_p$               | $A_n$                  | $a_n$               |
|:-----:|:----------------------:|:-------------------:|:----------------------:|:-------------------:|
| $A_p$ | $1$                    | $A_p = a_p n^b$     | $A_p = A_n n^{2(b-1)}$ | $A_p = a_n n^{b-2}$ |
| $a_p$ | $a_p = A_p n^{-b}$     | $1$                 | $a_p = A_n n^{b-2}$    | $a_p = a_n n^{-2}$  |
| $A_n$ | $A_n = A_p n^{2(1-b)}$ | $A_n = a_p n^{2-b}$ | $1$                    | $A_n = a_n n^{-b}$  |
| $a_n$ | $a_n = A_p n^{2-b}$    | $a_n = a_p n^2$     | $a_p = A_n n^b$        | $1$                 |


Light version. To read it, you need to do: $\text{row} = \text{col} \times \text{cell}$

|       | $A_p$        | $a_p$     | $A_n$        | $a_n$     |
|:-----:|:------------:|:---------:|:------------:|:---------:|
| $A_p$ | $1$          | $n^b$     | $n^{2(b-1)}$ | $n^{b-2}$ |
| $a_p$ | $n^{-b}$     | $1$       | $n^{b-2}$    | $n^{-2}$  |
| $A_n$ | $n^{2(1-b)}$ | $n^{2-b}$ | $1$          | $n^{-b}$  |
| $a_n$ | $n^{2-b}$    | $n^2$     | $n^b$        | $1$       |

There (will be/is) a function in `epiphy` to compute the transformation:

### Link between power law and aggregation parameter

$$
\theta = \frac{a_p - f(p)/n}{f(p) - a_p} \text{, with } f(p) = [p(1-p)]^{1-b}
$$




