# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

costTotiCPP <- function(i, flow, cost, type = "both", average = FALSE) {
    .Call('_epiphy_costTotiCPP', PACKAGE = 'epiphy', i, flow, cost, type, average)
}

costTotCPP <- function(flow, cost) {
    .Call('_epiphy_costTotCPP', PACKAGE = 'epiphy', flow, cost)
}

insertCPP <- function(vect, i, value) {
    .Call('_epiphy_insertCPP', PACKAGE = 'epiphy', vect, i, value)
}

ntotfoci <- function(nfoci, xrate, ngen, ngen_active) {
    .Call('_epiphy_ntotfoci', PACKAGE = 'epiphy', nfoci, xrate, ngen, ngen_active)
}

dispersalCPP <- function(nfoci, xrate, lambda, ngen, ngen_active = 0L) {
    .Call('_epiphy_dispersalCPP', PACKAGE = 'epiphy', nfoci, xrate, lambda, ngen, ngen_active)
}

collectCPP <- function(disperse, quadrat) {
    .Call('_epiphy_collectCPP', PACKAGE = 'epiphy', disperse, quadrat)
}

