# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

p_hscaled <- function(nodes, sites, bandwidth, edgeCorrection = FALSE) {
    .Call('_epiphy_p_hscaled', PACKAGE = 'epiphy', nodes, sites, bandwidth, edgeCorrection)
}

costTotiCPP <- function(i1, flow, cost, averaged = TRUE, absolute = FALSE) {
    .Call('_epiphy_costTotiCPP', PACKAGE = 'epiphy', i1, flow, cost, averaged, absolute)
}

costTotCPP <- function(flow, cost) {
    .Call('_epiphy_costTotCPP', PACKAGE = 'epiphy', flow, cost)
}

as_matrix_transport <- function(x, dim_mat) {
    .Call('_epiphy_as_matrix_transport', PACKAGE = 'epiphy', x, dim_mat)
}

